os: linux
dist: xenial
language: ruby
cache: bundler
rvm:
- 2.6.3

install:
  - bundle install

before_script:
  - git config --global user.email "jeonghyeon.rhea@gmail.com"
  - git config --global user.name "rhea-so"

script: bundle exec rake site:deploy --quiet #--trace

env:
  global:
   secure: "myrqwdzW8+APjRhXHHA8cCJA/XAAmpQTE+8VqtbujbAZ0aoDv64EE9EVdr7p7J3mZ39QPRw64xYEcUWpW/CnvlTAoffE5mqENnUwLaOqQKoEUn6QptKOyvsIHToDIou4TCsvhv0GyCdKBZbdne5jwpXBQSoZP/X/Acpn8TOW4+oQDIPfxIFYKa9oSmjVS+lxNOiC2Fj8HCLk4Sw2xlZYyOnrJD3lUmfgNfZ8Q4Ibs60WPK0PcCdDwAwV+MLTaI0mQZQTt972MUEmfV0Jh6sUBUn2+wOlr2n4LiikYhy/R0FuAAStYV0lf4fNxvnx2hwP631TDxDClVCFFB6myDaNLirPDuKrGSQZGGDlkYiO4xNkwBb+v51GmkIE/aL4VVFKzLa/EPbNNWddtcDFSLl8OR7enfLhGQRRBr0URiJ3/+m8Igcw6okMLraMoejVEFvev/MrsQr/Iigz8QeoLaaBvXLcZSQLu9FWCB97cM0AgP9u4oGtXOfB037w0otoHOan+HYnHz8NZftWIh0BZ3ugIVWSBH5FiZmhGLJphs8HVgfTKVesR7cabAt6M+OAK4dPy1P7ro1+q60HHPXms/7G5vbZaE3lQ8d5LkImEaU4AMeTXEl9Rig+KWGKk7Au/CVyitFsQ9N+y6YfhRbl51JXSLmiDmL6L0BGtIVCmTx+gAw="
branches:
  only:
    - main